[package]
name = "try-macro-proc_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.40"

[dependencies.syn]
version = "2.0.101"
default-features = false
features = ["full", "printing", "parsing", "proc-macro", "visit-mut"]
